//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prezente
    {
        public int Id { get; set; }
        public bool Prezenta { get; set; }
        public int StudentId { get; set; }
        public int EventId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Student Studenti { get; set; }
    }
}
