//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSchoolsEntities : DbContext
    {
        public dbSchoolsEntities()
            : base("name=dbSchoolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Curs> Cursuri { get; set; }
        public virtual DbSet<Profesor> Profesori { get; set; }
        public virtual DbSet<Sala> Sali { get; set; }
        public virtual DbSet<Student> Studenti { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<InscriereCursuri> InscriereCursuri { get; set; }
        public virtual DbSet<Prezente> Prezente { get; set; }
    }
}
